import{i,S as f}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const d=document.querySelector(".form"),c=document.querySelector(".gallery"),l=document.querySelector(".loader"),p={messageColor:"#FFF",color:"#EF4040",position:"topRight"};d.addEventListener("submit",g);function g(o){o.preventDefault(),c.innerHTML="";const r=o.target.elements.input.value;if(r.trim())l.classList.add("loading"),h(r),o.currentTarget.reset();else return i.error({title:"❕",theme:"light",message:"Please, fill in the search field",messageSize:"20px",messageColor:"#808080",backgroundColor:"#EF4040",position:"topLeft",timeout:2500})}function h(o){const r="https://pixabay.com",a="/api/",n=new URLSearchParams({key:"24543353-3824dfbf23e7b5ead533e5f72",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=r+a+"?"+n;fetch(e).then(t=>t.json()).then(t=>{const s=t.hits;s.length===0&&y(),L(s)}).catch(t=>{i.error({...p,message:`${t}`})}).finally(()=>l.classList.remove("loading"))}function y(){i.error({...p,message:"Sorry, there are no images matching your search query. Please try again!"})}function L(o){const r=o.map(({largeImageURL:a,webformatURL:n,tags:e,likes:t,views:s,comments:u,downloads:m})=>`<li class='gallery-item'>
  <a class='gallery-link' href='${a}'>
    <img class='gallery-image' src='${n}' alt='${e}'/>
  </a>
<div class='container-app'>
<p><span>Likes</span> ${t}</p>
<p><span>Views</span> ${s}</p>
<p><span>Comments</span> ${u}</p>
<p><span>Downloads</span> ${m}</p>
</div>
 </li>`).join("");c.insertAdjacentHTML("afterBegin",r),S()}const P=new f(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});function S(){P.refresh()}
//# sourceMappingURL=commonHelpers.js.map
